version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5555:5432
    environment:
      - POSTGRES_PASSWORD=randomPassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=news

  frontend:
    build:
        context: ./frontend   # path to your React app folder
        dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://host.docker.internal:8080/
